# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-06-13 07:54
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BugList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('title', models.CharField(blank=True, max_length=256, null=True, verbose_name='标题名称')),
                ('context', models.TextField(blank=True, null=True, verbose_name='描述内容')),
                ('level', models.IntegerField(blank=True, choices=[(1, '建议'), (2, '待优化'), (3, '功能'), (4, '高危'), (5, '致命')], null=True, verbose_name='')),
                ('resolver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='solve_user', to=settings.AUTH_USER_MODEL, verbose_name='')),
                ('submitter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_user', to=settings.AUTH_USER_MODEL, verbose_name='')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
