# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-27 13:35
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [

    ]

