# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-05-08 07:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cmdb', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('vps_id', models.CharField(blank=True, default=' ', max_length=255, null=True, unique=True, verbose_name='实例ID')),
                ('vps_name', models.CharField(blank=True, default=' ', max_length=255, null=True, unique=True, verbose_name='实例名称')),
                ('intral_ip', models.GenericIPAddressField(blank=True, null=True, unique=True, verbose_name='内网IP')),
                ('intral_net', models.CharField(blank=True, default=' ', max_length=255, null=True, verbose_name='内网网段')),
                ('internet_ip', models.GenericIPAddressField(blank=True, null=True, unique=True, verbose_name='外网IP')),
                ('system_version', models.CharField(blank=True, default=' ', max_length=255, null=True, verbose_name='系统版本')),
                ('core_cpu', models.IntegerField(blank=True, null=True, verbose_name='cpu个数')),
                ('memory', models.IntegerField(blank=True, null=True, verbose_name='内存')),
                ('status', models.IntegerField(blank=True, choices=[(1, '运行'), (2, '停止')], default=1, null=True, verbose_name='状态')),
                ('buy_date', models.DateTimeField(blank=True, null=True, verbose_name='购买日期')),
                ('deadline', models.DateTimeField(blank=True, null=True, verbose_name='过期日期')),
                ('comment', models.CharField(blank=True, max_length=255, null=True, verbose_name='备注')),
            ],
            options={
                'verbose_name': '项目',
                'verbose_name_plural': '项目',
            },
        ),
        migrations.CreateModel(
            name='Backend_Server',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('weight', models.CharField(blank=True, max_length=255, null=True, verbose_name='权重')),
                ('status', models.CharField(blank=True, max_length=255, null=True, verbose_name='状态')),
                ('listen_ports', models.CharField(blank=True, max_length=255, null=True, verbose_name='监听端口')),
                ('comment', models.CharField(blank=True, default=' ', max_length=255, null=True, verbose_name='备注')),
            ],
            options={
                'verbose_name': '后端服务器',
                'verbose_name_plural': '后端服务器',
            },
        ),
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('domain_name', models.CharField(max_length=255, verbose_name='域名名称')),
                ('domain_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='域名ID')),
                ('dns_servers', models.CharField(blank=True, max_length=255, null=True, verbose_name='DNS服务器')),
                ('ali_domain', models.NullBooleanField(default=True, verbose_name='阿里云域名')),
                ('version_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='厂商')),
                ('comment', models.CharField(blank=True, default=' ', max_length=255, null=True, verbose_name='备注')),
            ],
            options={
                'verbose_name': '域名信息',
                'verbose_name_plural': '域名信息',
            },
        ),
        migrations.CreateModel(
            name='Domain_Records',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('rr', models.CharField(blank=True, max_length=255, null=True, verbose_name='记录')),
                ('status', models.CharField(blank=True, max_length=255, null=True, verbose_name='状态')),
                ('value', models.CharField(blank=True, max_length=255, null=True, verbose_name='解析值')),
                ('type', models.CharField(blank=True, max_length=255, null=True, verbose_name='记录类型')),
                ('lock', models.NullBooleanField(default=False, verbose_name='上锁')),
                ('line', models.CharField(blank=True, max_length=255, null=True, verbose_name='解析线路')),
                ('ttl', models.CharField(blank=True, max_length=255, null=True, verbose_name='生存值')),
                ('comment', models.CharField(blank=True, default=' ', max_length=255, null=True, verbose_name='备注')),
                ('asset_ip', models.ManyToManyField(blank=True, null=True, related_name='domain_records3', to='cmdb.Assets', verbose_name='内网Ip')),
                ('name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='domain_records1', to='cmdb.Domain', verbose_name='域名名称')),
            ],
            options={
                'verbose_name': '域名记录',
                'verbose_name_plural': '域名记录',
            },
        ),
        migrations.CreateModel(
            name='Key',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('access_key', models.CharField(max_length=255, verbose_name='密钥ID')),
                ('key_secret', models.CharField(max_length=255, verbose_name='密匙')),
                ('comment', models.CharField(blank=True, max_length=255, null=True, verbose_name='备注')),
            ],
            options={
                'verbose_name': '密钥',
                'verbose_name_plural': '密钥',
            },
        ),
        migrations.CreateModel(
            name='Lb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('name', models.CharField(max_length=255, verbose_name='LB名称')),
                ('load_balancer_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='LBID')),
                ('resource_group_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='组ID')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, unique=True, verbose_name='IP')),
                ('status', models.IntegerField(blank=True, choices=[(1, '激活'), (2, '停止')], default=1, null=True, verbose_name='状态')),
                ('ip_type', models.CharField(blank=True, max_length=255, null=True, verbose_name='IP类型')),
                ('region_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='区域id')),
                ('listen_ports', models.CharField(blank=True, max_length=255, null=True, verbose_name='监听端口')),
                ('listen_protocal', models.CharField(blank=True, max_length=255, null=True, verbose_name='监听协议')),
                ('buy_date', models.DateTimeField(blank=True, null=True, verbose_name='购买日期')),
                ('comment', models.CharField(blank=True, default=' ', max_length=255, null=True, verbose_name='备注')),
            ],
            options={
                'verbose_name': '负载均衡',
                'verbose_name_plural': '负载均衡',
            },
        ),
        migrations.CreateModel(
            name='Password',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('port', models.CharField(blank=True, max_length=255, null=True, verbose_name='端口')),
                ('user', models.CharField(blank=True, max_length=255, null=True, verbose_name='用户')),
                ('password', models.CharField(blank=True, max_length=255, null=True, verbose_name='密码')),
                ('comment', models.CharField(blank=True, max_length=255, null=True, verbose_name='备注')),
                ('ip', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ip', to='cmdb.Assets', verbose_name='资产ip')),
            ],
            options={
                'verbose_name': '密码表',
                'verbose_name_plural': '密码表',
            },
        ),
        migrations.CreateModel(
            name='Product_line',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('name', models.CharField(max_length=255, verbose_name='产品线')),
                ('comment', models.CharField(blank=True, max_length=255, null=True, verbose_name='备注')),
            ],
            options={
                'verbose_name': '产品线',
                'verbose_name_plural': '产品线',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('env', models.IntegerField(blank=True, choices=[(1, '正式'), (2, '测试')], default=0, null=True, verbose_name='环境')),
                ('domain', models.CharField(blank=True, max_length=255, null=True, verbose_name='域名')),
                ('website', models.CharField(blank=True, max_length=255, null=True, verbose_name='网址')),
                ('name', models.CharField(max_length=255, verbose_name='项目')),
                ('path', models.CharField(blank=True, default='null', max_length=255, null=True, verbose_name='路径')),
                ('comment', models.CharField(blank=True, max_length=255, null=True, verbose_name='备注')),
                ('asset', models.ManyToManyField(related_name='asset', to='cmdb.Assets', verbose_name='内网ip')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product', to='cmdb.Product_line', verbose_name='产品')),
            ],
            options={
                'verbose_name': '项目',
                'verbose_name_plural': '项目',
            },
        ),
        migrations.CreateModel(
            name='Website',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='网址')),
                ('use', models.CharField(max_length=255, verbose_name='用途')),
                ('user', models.CharField(blank=True, max_length=255, null=True, verbose_name='登录账号')),
                ('password', models.CharField(blank=True, max_length=255, null=True, verbose_name='登录密码')),
                ('comment', models.CharField(blank=True, max_length=255, null=True, verbose_name='备注')),
            ],
            options={
                'verbose_name': '项目',
                'verbose_name_plural': '项目',
            },
        ),
        migrations.CreateModel(
            name='Yun_Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('name', models.CharField(max_length=255, verbose_name='云账号')),
                ('comment', models.CharField(blank=True, default=' ', max_length=255, null=True, verbose_name='备注')),
            ],
            options={
                'verbose_name': '云账号',
                'verbose_name_plural': '云账号',
            },
        ),
        migrations.AddField(
            model_name='lb',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lb', to='cmdb.Yun_Account', verbose_name='云账号'),
        ),
        migrations.AddField(
            model_name='key',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='account', to='cmdb.Yun_Account', verbose_name='云账号'),
        ),
        migrations.AddField(
            model_name='domain_records',
            name='slb_ip',
            field=models.ManyToManyField(blank=True, null=True, related_name='domain_records2', to='cmdb.Lb', verbose_name='SlbIp'),
        ),
        migrations.AddField(
            model_name='domain',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='domain', to='cmdb.Yun_Account', verbose_name='云账号'),
        ),
        migrations.AddField(
            model_name='backend_server',
            name='lb',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lbid', to='cmdb.Lb', verbose_name='LB名称'),
        ),
        migrations.AddField(
            model_name='backend_server',
            name='server_id',
            field=models.ManyToManyField(blank=True, null=True, related_name='assets', to='cmdb.Assets', verbose_name='内网ip'),
        ),
        migrations.AddField(
            model_name='assets',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='account_1', to='cmdb.Yun_Account', verbose_name='所属账号'),
        ),
    ]
