# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-05-08 09:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0002_auto_20180508_1548'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='domain_records',
            name='asset_ip',
        ),
        migrations.AddField(
            model_name='domain_records',
            name='asset_ip',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='domain_records3', to='cmdb.Assets', verbose_name='内网Ip'),
        ),
        migrations.RemoveField(
            model_name='domain_records',
            name='slb_ip',
        ),
        migrations.AddField(
            model_name='domain_records',
            name='slb_ip',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='domain_records2', to='cmdb.Lb', verbose_name='SlbIp'),
        ),
    ]
