# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-06-25 08:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0002_auto_20180514_0237'),
    ]

    operations = [
        migrations.CreateModel(
            name='Docker_Registry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('name', models.CharField(max_length=255, verbose_name='仓库名称')),
                ('comment', models.CharField(blank=True, default=' ', max_length=255, null=True, verbose_name='备注')),
            ],
            options={
                'verbose_name': 'docker_registry',
                'verbose_name_plural': 'docker_registry',
            },
        ),
        migrations.CreateModel(
            name='Docker_Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('tag', models.CharField(blank=True, max_length=255, null=True, verbose_name='版本')),
                ('cmd', models.CharField(blank=True, max_length=255, null=True, verbose_name='cmd')),
                ('comment', models.CharField(blank=True, default=' ', max_length=255, null=True, verbose_name='备注')),
                ('registry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dockerid', to='cmdb.Docker_Registry', verbose_name='registry名称')),
            ],
            options={
                'verbose_name': 'docker_tag',
                'verbose_name_plural': 'docker_tag',
            },
        ),
    ]
